"""hostctl -- run commands and access files on a host, local or remote.

Protocol-agnostic host management: concrete hosts expose only the operations
their providers support. Shell dialect and path flavor remain explicit where
the transport cannot identify them.
"""

from __future__ import annotations

try:
    from importlib.metadata import PackageNotFoundError, version as _version

    __version__ = _version("hostctl")
except PackageNotFoundError:  # not installed (e.g. running from a bare checkout)
    __version__ = "0.0.0.dev0"

from .executor import (
    CaptureOutput as CaptureOutput,
    ContainerExecutor as ContainerExecutor,
    CommandArgument as CommandArgument,
    Environment as Environment,
    Executor as Executor,
    ExecutorCapability as ExecutorCapability,
    ExecutorCommand as ExecutorCommand,
    ExecutionOptions as ExecutionOptions,
    FileHandle as FileHandle,
    Input as Input,
    LocalExecutor as LocalExecutor,
    NativeWinRMSession as NativeWinRMSession,
    PsrpExecutor as PsrpExecutor,
    pypsrp_available as pypsrp_available,
    require_pypsrp as require_pypsrp,
    PathLike as PathLike,
    QemuExecutor as QemuExecutor,
    SerialExecutor as SerialExecutor,
    SerialFactory as SerialFactory,
    SerialLike as SerialLike,
    SerialSettings as SerialSettings,
    SerialTransport as SerialTransport,
    SshExecutor as SshExecutor,
    WinRMExecutor as WinRMExecutor,
)
from .host import (
    ContainerConfig as ContainerConfig,
    ContainerHost as ContainerHost,
    ContainerPathBackend as ContainerPathBackend,
    Host as Host,
    HostConfig as HostConfig,
    HostInfo as HostInfo,
    HostPath as HostPath,
    LocalConfig as LocalConfig,
    LocalHost as LocalHost,
    PathnameConstructor as PathnameConstructor,
    PosixContainerPath as PosixContainerPath,
    PosixQemuPath as PosixQemuPath,
    QemuConfig as QemuConfig,
    QemuHost as QemuHost,
    QgaPathBackend as QgaPathBackend,
    SshConfig as SshConfig,
    SerialConfig as SerialConfig,
    SerialHost as SerialHost,
    WinRMConfig as WinRMConfig,
    WinRMProvider as WinRMProvider,
    WinRMPath as WinRMPath,
    WinRMPathBackend as WinRMPathBackend,
    WindowsContainerPath as WindowsContainerPath,
    WindowsQemuPath as WindowsQemuPath,
    SystemConfig as SystemConfig,
    SystemHost as SystemHost,
    PosixConfig as PosixConfig,
    PosixHost as PosixHost,
    WindowsConfig as WindowsConfig,
    WindowsHost as WindowsHost,
    IosConfig as IosConfig,
    IosHost as IosHost,
    CompositePath as CompositePath,
)
from .provider import (
    ExecutorProvider as ExecutorProvider,
    OperationNotStarted as OperationNotStarted,
    PathProvider as PathProvider,
    ProviderProbe as ProviderProbe,
    ProviderSelection as ProviderSelection,
    ProviderSelector as ProviderSelector,
    SessionInitializer as SessionInitializer,
)
from .executor._qga import (
    GuestAgentTransport as GuestAgentTransport,
    LibvirtGuestAgentTransport as LibvirtGuestAgentTransport,
    QgaCommandError as QgaCommandError,
    QgaProtocolError as QgaProtocolError,
    SshUnixGuestAgentTransport as SshUnixGuestAgentTransport,
    UnixSocketGuestAgentTransport as UnixSocketGuestAgentTransport,
)
from .process import (
    ContainerProcess as ContainerProcess,
    Process as Process,
    ProcessData as ProcessData,
    QemuSerialConsole as QemuSerialConsole,
    QemuSerialProcess as QemuSerialProcess,
    SerialProcess as SerialProcess,
    SerialConsoleProcess as SerialConsoleProcess,
    SshProcess as SshProcess,
    PipelineResult as PipelineResult,
    PipelineStreams as PipelineStreams,
    RunspaceSession as RunspaceSession,
    TerminalOptions as TerminalOptions,
    TerminalRequest as TerminalRequest,
)
from .serial import (
    ConsoleProtocolError as ConsoleProtocolError,
    LoginStep as LoginStep,
    PromptConsoleProfile as PromptConsoleProfile,
    RawConsoleProfile as RawConsoleProfile,
    SerialConsoleProtocol as SerialConsoleProtocol,
)
from .sync import (
    ProgressReader as ProgressReader,
    host_checksum as host_checksum,
    stat_checksum as stat_checksum,
)
from .shell import (
    BASH as BASH,
    CMD as CMD,
    FISH as FISH,
    POWERSHELL as POWERSHELL,
    POSIX_SHELL as POSIX_SHELL,
    PWSH as PWSH,
    ZSH as ZSH,
    BashShellFlavour as BashShellFlavour,
    CmdShellFlavour as CmdShellFlavour,
    FishShellFlavour as FishShellFlavour,
    PosixShellFlavour as PosixShellFlavour,
    PowerShellFlavour as PowerShellFlavour,
    Shell as Shell,
    ShellCommand as ShellCommand,
    ShellFlavour as ShellFlavour,
    ShellFlavourSelection as ShellFlavourSelection,
    ShellOperator as ShellOperator,
    ShellSession as ShellSession,
    ShellToken as ShellToken,
    ZshShellFlavour as ZshShellFlavour,
    register_shell_flavour as register_shell_flavour,
    shell_flavour as shell_flavour,
)

__all__ = [
    "Host",
    "HostConfig",
    "HostInfo",
    "HostPath",
    "ContainerConfig",
    "ContainerExecutor",
    "ContainerHost",
    "ContainerPathBackend",
    "ContainerProcess",
    "PipelineResult",
    "PipelineStreams",
    "RunspaceSession",
    "Executor",
    "ExecutorCapability",
    "CommandArgument",
    "ExecutorCommand",
    "ExecutionOptions",
    "CaptureOutput",
    "Environment",
    "FileHandle",
    "Input",
    "LocalExecutor",
    "NativeWinRMSession",
    "PsrpExecutor",
    "pypsrp_available",
    "require_pypsrp",
    "PathLike",
    "SshExecutor",
    "WinRMExecutor",
    "LocalHost",
    "LocalConfig",
    "BASH",
    "CMD",
    "FISH",
    "POWERSHELL",
    "POSIX_SHELL",
    "PWSH",
    "ZSH",
    "BashShellFlavour",
    "CmdShellFlavour",
    "FishShellFlavour",
    "PathnameConstructor",
    "PosixContainerPath",
    "PosixQemuPath",
    "Process",
    "ProcessData",
    "QemuConfig",
    "QemuExecutor",
    "QemuHost",
    "QemuSerialConsole",
    "QemuSerialProcess",
    "QgaPathBackend",
    "QgaCommandError",
    "QgaProtocolError",
    "GuestAgentTransport",
    "LibvirtGuestAgentTransport",
    "SerialExecutor",
    "SerialFactory",
    "SerialLike",
    "SerialProcess",
    "SerialConsoleProcess",
    "SerialConfig",
    "SerialHost",
    "SerialConsoleProtocol",
    "RawConsoleProfile",
    "PromptConsoleProfile",
    "ProgressReader",
    "LoginStep",
    "ConsoleProtocolError",
    "SerialSettings",
    "SerialTransport",
    "PosixShellFlavour",
    "PowerShellFlavour",
    "Shell",
    "ShellCommand",
    "ShellFlavour",
    "ShellFlavourSelection",
    "ShellOperator",
    "ShellSession",
    "ShellToken",
    "ZshShellFlavour",
    "register_shell_flavour",
    "shell_flavour",
    "host_checksum",
    "stat_checksum",
    "SshConfig",
    "SshProcess",
    "SshUnixGuestAgentTransport",
    "TerminalOptions",
    "TerminalRequest",
    "WinRMConfig",
    "WinRMProvider",
    "WinRMPath",
    "WinRMPathBackend",
    "WindowsContainerPath",
    "WindowsQemuPath",
    "SystemConfig",
    "SystemHost",
    "PosixConfig",
    "PosixHost",
    "WindowsConfig",
    "WindowsHost",
    "IosConfig",
    "IosHost",
    "CompositePath",
    "ExecutorProvider",
    "OperationNotStarted",
    "PathProvider",
    "ProviderProbe",
    "ProviderSelection",
    "ProviderSelector",
    "SessionInitializer",
    "UnixSocketGuestAgentTransport",
    "__version__",
]
